version: '{branch}-{build}'
branches:
  except:
  - gh-pages
build:
  project: ArachNGIN.sln
  parallel: true
  verbosity: normal
configuration:
- Debug
- Release
artifacts:
- path: ArachNGIN_release*.zip
  name: Release
- path: ArachNGIN_debug*.zip
  name: Debug
deploy: off
before_build:
- cmd: >-
    nuget restore

after_build:
- cmd: >-
    call GitVersioner.bat ba
    
    call GitVersioner.bat w zip.bat

    call zip.bat

    call GitVersioner.bat r zip.bat
test_script:
- cmd: vstest.console /logger:Appveyor _bin\$(configuration).Tests\ArachNGIN.Tests.dll